name: Deploy to Hetzner

on:
    push:
        branches: [ main ]

jobs:
    deploy:
        name: Deploy Symfony App
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up SSH
              run: |
                  mkdir -p ~/.ssh
                  echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
                  chmod 600 ~/.ssh/id_ed25519
                  ssh-keyscan -H ${{ secrets.HETZNER_HOST }} >> ~/.ssh/known_hosts

            - name: Deploy to Hetzner
              run: |
                  ssh pvr@${{ secrets.HETZNER_HOST }} << 'EOF'
                    cd /opt/symfony
                    git pull origin main
                    docker exec symfony-web-1 composer install --no-interaction --no-dev --optimize-autoloader
                    docker exec symfony-web-1 php bin/console cache:clear
                    docker restart symfony-web-1
                  EOF
